// Generated by https://quicktype.io

import { ContingentVechileType } from "@prisma/client";
import type { z } from "zod";

export interface BookingFormData {
  bookerName: string;
  bookerPhone: string;
  province: string;
  city: string;
  regionCoordinatorName: string;
  regionCoordinatorPhone: string;
  contingents: Contingent[];
}

export interface Contingent {
  personCount: number;
  vechileType: z.infer<typeof ContingentVechileType>;
  contingentCoordinatorName: string;
  contingentCoordinatorPhone: string;
}
